# Generated by Django 5.2.9 on 2025-12-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('technologies', models.CharField(max_length=200, verbose_name='Tecnologías (separadas por coma)')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Imagen del Proyecto')),
                ('link_github', models.URLField(blank=True, verbose_name='Enlace GitHub')),
                ('link_live', models.URLField(blank=True, verbose_name='Enlace Demo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
