# Generated by Django 5.2.9 on 2025-12-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='project',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='¿Es el Principal?'),
        ),
    ]
