# Generated by Django 5.2.9 on 2025-12-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_message_project_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='¿Es Principal?'),
        ),
    ]
